### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '+'

### ISSUE THREAD

**Issue by Vitexus** [notsatan/go-template#37]
```
vitex@NAX008380:~/Projects/Custom/Packaging$ cookiecutter gh:notsatan/go-template
project_name [go-template]: KbHostnames2Networks
project_description [Kbhostnames2Networks is a Go application created using https://github.com/notsatan/go-template]:
go_module_path [github.com/notsatan/go-template]: git.xx.cz/users/xxxx/repos/hostnames2networks
license_owner [notsatan]: XX a.s.
base_branch [master]:
contact_email []: vitezslav_dvorak@xx.cz
github_specific_features [y]: n
use_codecov [y]: n
use_precommit [y]: n
Select go_version:
1 - 1.17
2 - 1.16
3 - 1.18
Choose from 1, 2, 3 [1]: 2
Select license:
1 - MIT
2 - BSD-3
3 - GNU GPL v3.0
4 - Apache Software License 2.0
Choose from 1, 2, 3, 4 [1]: 1
Traceback (most recent call last):
  File "/home/vitex/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vitex/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/home/vitex/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/home/vitex/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/home/vitex/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./Makefile", line 47, in <module>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 386, in expect
    raise TemplateSyntaxError("expected token %r, got %r" %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '+'
  File "./Makefile", line 47
    {%- endif +%}
```

**Comment by notsatan** [comment]
Hi Vitexus, I tried to create a project using `go-template` with the same parameters as you specified, and everything went as expected with no crashes.

```text
$ cookiecutter --version
Cookiecutter 2.1.1 from /home/notsatan/.local/lib/python3.10/site-packages (Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0])
$
$ cookiecutter gh:notsatan/go-template
project_name [go-template]: KbHostnames2Networks
project_description [Kbhostnames2Networks is a Go application created using https://github.com/notsatan/go-template]: 
go_module_path [github.com/notsatan/go-template]: git.xx.cz/users/xxxx/repos/hostnames2networks
license_owner [notsatan]: XX a.s.
base_branch [master]: 
contact_email []: vitezslav_dvorak@xx.cz
github_specific_features [y]: n
use_codecov [y]: n
use_precommit [y]: n
Select go_version:
1 - 1.17
2 - 1.16
3 - 1.18
Choose from 1, 2, 3 [1]: 2
Select license:
1 - MIT
2 - BSD-3
3 - GNU GPL v3.0
4 - Apache Software License 2.0
Choose from 1, 2, 3, 4 [1]: 1

====================================================================================

Your project `KbHostnames2Networks` is ready!

It is suggested to go through the generated `README` for detailed instructions on
how to use the tools that come with `go-template`! The following is a *brief*
overview of steps to push code to remote.

1) Move to project directory, and initialize a git repository:
    $ cd KbHostnames2Networks && git init

2) Run codestyle:
    $ make codestyle

3) Run linters and codestyle checkers
    $ make lint

4) Run the complete test-suite:
    $ make test

7) Upload initial code to git:
    $ git add -a
    $ git commit -m "Initial commit!"
    $ git remote add origin https://git.xx.cz/users/xxxx/repos/hostnames2networks.git
    $ git push -u origin --all

If you have any suggestions, or encounter any issue, please raise an issue;
    https://github.com/notsatan/go-template

```

Which version of Cookiecutter were you using when you ran into this error? Can you re-try this with the latest version of [Cookiecutter][cookiecutter]? My guess is that you're using an outdated version of Cookiecutter that did not support the `+` token in the template syntax, in this case, simply updating Cookiecutter should fix your issue!


```shell
$ pip install --upgrade cookiecutter
```

P.S. You can use a [virtual environment][venv] to install (a localized) version of Cookiecutter that is up-to-date in case you can't (or don't want to) modify the central installation.

[venv]: https://docs.python.org/3/tutorial/venv.html
[cookiecutter]: https://pypi.org/project/cookiecutter/

**Comment by notsatan** [comment]
Hey @Vitexus, any updates on this so far?

**Comment by notsatan** [comment]
Closing this issue, feel free to revert back if the issue still persists!

**Comment by arsto27** [comment]
işe yaramadı bende

**Comment by notsatan** [comment]
> It didn't work for me

Thanks, Google Translate. Now @arsto27 I'm happy to reopen this issue (or you can raise a new one and link it to this one), as long as:

- You actually describe your problem, and hopefully include an error log that I can use to debug the issue
- You stick to English (I don't know Turkish, and Google Translate often fails for technical translations)
